### ISSUE TITLE
vim plugin fzf

### ISSUE THREAD

**Issue by jrock2004** [NullVoxPopuli/dotfiles#10]
I noticed in your plugins.vim you have the following line, but with it, every time I update my plugins I get an error on fzf.

```
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
```

I think you can just get away with doing this and that error goes away when doing a `PlugUpdate`

```
Plug 'junegunn/fzf', { 'dir': '/usr/local/opt/fzf' }
```

Maybe you do not see the error when you update?

**Comment by NullVoxPopuli** [comment]
yeah, fzf updates just fine for me :man_shrugging:

**Comment by jrock2004** [comment]
I figured out why, on my mac I install via brew where you on linux are probably using command line
